# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: tranduylong0306@gmail.com
author_name: LongTran
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: jlx
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension for cell IDs
python_name: jlx
repository: https://github.com/DanCat6300/jlx
test: false
viewer_name: ''

